sudo: false
language: android
jdk: oraclejdk8

env:
  global:
  - ANDROID_API=28
  - ANDROID_BUILD_TOOLS=28.0.0

android:
  components:
  - platform-tools
  - tools
  - build-tools-$ANDROID_BUILD_TOOLS
  - android-$ANDROID_API
  - extra-google-m2repository
  - extra-android-m2repository
  - addon-google_apis-google-28
  licenses:
  - android-sdk-preview-license-.+
  - android-sdk-license-.+
  - google-gdk-license-.+

before_install:
- chmod +x gradlew

script:
#connectedCheck
- "./gradlew clean build check -PdisablePreDex --stacktrace"

notifications:
  email: true
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.gradle"
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"


